[package]
name    = "common_enums"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dummy_connector = []

[dependencies]
diesel = { version = "2.1.0", features = ["postgres"] }
serde  = { version = "1.0.160", features = [ "derive" ] }
serde_json = "1.0.96"
strum  = { version = "0.24.1", features = [ "derive" ] }
time = { version = "0.3.20", features = ["serde", "serde-well-known", "std"] }
utoipa = { version = "3.3.0", features = ["preserve_order"] }

# First party crates
common_utils = { version = "0.1.0", path = "../common_utils" }
router_derive = { version = "0.1.0", path = "../router_derive" }

[dev-dependencies]
serde_json = "1.0.96"
